import type { Metadata } from "next";
import { Sriracha } from "next/font/google";
import "./globals.css";
import Navbar from "@/features/navbar";
import QueryClientWrapper from "@/components/queryProvider";
import { Toaster } from "sonner";

const sriracha = Sriracha({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sriracha.className} antialiased bg-background text-foreground scroll-smooth`}
      >
        <Navbar />
        <main className="pt-16">
          <QueryClientWrapper>{children}</QueryClientWrapper>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
